#!/bin/sh -e

oname=dplyr
pkg=r-cran-`echo $oname | tr '[A-Z]' '[a-z]'`

if [ "$AUTOPKGTEST_TMP" = "" ] ; then
  AUTOPKGTEST_TMP=`mktemp -d /tmp/${pkg}-test.XXXXXX`
  trap "rm -rf $AUTOPKGTEST_TMP" 0 INT QUIT ABRT PIPE TERM
fi
cd $AUTOPKGTEST_TMP
cp -a /usr/share/doc/${pkg}/tests/* $AUTOPKGTEST_TMP
find . -name "*.gz" -exec gunzip \{\} \;
# There is no package r-cran-lahman available yet
for testfile in testthat/* ; do
    if grep -q lahman $testfile ; then
        rm $testfile
    fi
done
sed -i '/[Ll]ahman/d' testthat.R
LC_ALL=C.UTF-8 R --no-save < testthat.R
